### ISSUE TITLE
同款需求，哥们啥时候弄好呀

### ISSUE THREAD

**Issue by kennygp** [LewinJun/react-native-lewin-cl-shanyan#1]
哥们啥时候能搞好呀？先谢谢咯

**Comment by LewinJun** [comment]
我正在写，可能还有小部分 bug, 今天接入到我的项目  可以用了

**Comment by LewinJun** [comment]
文档还没来得及写 ，可以看Example里面配置

**Comment by LewinJun** [comment]
[微信群](https://dist-client.oss-cn-shanghai.aliyuncs.com/WechatIMG451.png )  加入群聊及时通知

**Comment by LewinJun** [comment]
已经全部好了啊，可以接入了。   ios  授权登录 超时 和官方的开发人员 讨论很久，  sdk有个小bug

**Comment by kennygp** [comment]
好的。先行谢过

**Comment by LewinJun** [comment]
ios  超时好了  官方sdk最新版 没有这个问题了。  升级到1.0.7   新版sdk 弹框授权  还没有封装，如果有人需要再封装
