### ISSUE TITLE
填写logo 提示 value for logo cannot be cast from Double to String 

### ISSUE THREAD

**Issue by premillos** [LewinJun/react-native-lewin-cl-shanyan#2]
![image](https://user-images.githubusercontent.com/16378134/69702665-ad2e1b00-112a-11ea-963a-f45f45e3e9aa.png)

要是能加个微信沟通下就好了，很棒的项目

**Comment by pssgo** [comment]
而且好多参数 不生效,是我的姿势问题吗

**Comment by premillos** [comment]
还是接入原生解决了这个
